/*!
 * \file chunk_gated_delta_rule_fwd_h_tiling_key.h
 * \brief Tiling 模板参数定义
 */

#ifndef __CHUNKGATEDDELTARULEFWDH_TILING_KEY_H__
#define __CHUNKGATEDDELTARULEFWDH_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_0 0
#define CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_1 1
#define CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_2 2
#define CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_3 3
#define CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_4 4
#define CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_5 5
#define CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_6 6
#define CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_7 7

ASCENDC_TPL_ARGS_DECL(
    ChunkGatedDeltaRuleFwdH,
    ASCENDC_TPL_UINT_DECL(
        schMode, 3, ASCENDC_TPL_UI_LIST,
        CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_0, CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_1,
        CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_2, CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_3,
        CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_4, CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_5,
        CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_6, CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_7));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(
        schMode, ASCENDC_TPL_UI_LIST,
        CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_0, CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_1,
        CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_2, CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_3,
        CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_4, CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_5,
        CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_6, CHUNKGATEDDELTARULEFWDH_TPL_SCH_MODE_7)));

#endif
